config/routes.rb
Rails.application.routes.draw do
  get "sessions/new"
  root "static_pages#home"
  get "help" => "static_pages#help"
  get "about" => "static_pages#about"
  get "contact" => "static_pages#contact"
  get "signup" => "users#new"
  get "login" => "sessions#new"
  post "login" => "sessions#create"
  delete "logout" => "sessions#destroy"
  resources :users do
    member do
      get :following, :followers
    end
  end
  resources :microposts, only: [:create, :destroy]
  resources :relationships, only: [:create, :destroy]
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/micropost.rb
class Micropost < ApplicationRecord
  belongs_to :user
  default_scope -> { order(created_at: :desc)}
  validates :user_id, presence: true
  validates :content, presence: true, length: { maximum: 255}
end

app/models/relationship.rb
class Relationship < ApplicationRecord
    belongs_to :follower, class_name: "User"
    belongs_to :followed, class_name: "User"
    validates :follower_id, presence: true
    validates :followed_id, presence: true
end

app/models/user.rb
class User < ApplicationRecord
    has_many :microposts, dependent: :destroy
    has_many :active_relationships, class_name: "Relationship", foreign_key: "follower_id", dependent: :destroy
    has_many :following, through: :active_relationships, source: :followed
    has_many :passive_relationships, class_name: "Relationship", foreign_key: "followed_id", dependent: :destroy
    has_many :followers, through: :passive_relationships, source: :follower
    before_save { self.email = email.downcase }
    validates :name, presence: true, length: { maximum:50 }
    VALID_EMAIL_REGEX = /\A[\w+\-.]+@[a-z\d\-.]+\.[a-z]+\z/i
    validates :email, presence: true, length: { maximum:255 }, format: { with: VALID_EMAIL_REGEX }, uniqueness: { case_sensitive: false}

    has_secure_password
    validates :password, length: { minimum:6 }

    def feed
        following_ids_subselect = "SELECT followed_id FROM relationships WHERE follower_id = :user_id"
        Micropost.where("user_id IN (#{following_ids_subselect}) OR user_id = :user_id", user_id: id)
    end

    def follow(other_user)
        active_relationships.create(followed_id: other_user.id)
    end

    def unfollow(other_user)
        active_relationships.find_by(followed_id: other_user.id).destroy
    end

    def following?(other_user)
        following.include?(other_user)
    end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Only allow modern browsers supporting webp images, web push, badges, import maps, CSS nesting, and CSS :has.
  allow_browser versions: :modern
  include SessionsHelper

  def logged_in_user
      unless logged_in?
        flash[:danger] = "Please Login"
        redirect_to login_url
      end
    end
end

app/controllers/microposts_controller.rb
class MicropostsController < ApplicationController
    before_action :logged_in_user, only: [:create, :destroy]
    before_action :correct_user, only: :destroy

    def create
        @micropost = @current_user.microposts.build(micropost_params)
        if @micropost.save
            flash[:success] = "Micropost Created!"
            redirect_to root_url
        else
            @feed_items = []
            render 'static_pages/home', status: :unprocessable_entity
        end
    end

    def destroy
        @micropost.destroy
        flash[:success] = "Micropost deleted"
        redirect_to request.referrer || root_url
    end

    private
        def micropost_params
            params.require(:micropost).permit(:content)
        end

        def correct_user
            @micropost = current_user.microposts.find_by(id: params[:id])
            redirect_to root_url, status: :see_other if @micropost.nil?
        end
end

app/controllers/relationships_controller.rb
class RelationshipsController < ApplicationController
    before_action :logged_in_user

    def create
        user = User.find(params[:followed_id])
        current_user.follow(user)
        redirect_to user
    end

    def destroy
        user = Relationship.find(params[:id]).followed
        current_user.unfollow(user)
        redirect_to user
    end
end

app/controllers/sessions_controller.rb
class SessionsController < ApplicationController
  def new
  end
  def create
    user = User.find_by(email: params[:session][:email].downcase)
    if user && user.authenticate(params[:session][:password])
      log_in user
      redirect_to user
    else
      flash.now[:danger] = "Invalid email/password"
      render 'new'
    end
  end
  def destroy
    log_out
    redirect_to root_url
  end
end

app/controllers/static_pages_controller.rb
class StaticPagesController < ApplicationController
  def home
    if logged_in?
      @micropost = current_user.microposts.build
      @feed_items = current_user.feed.paginate(page: params[:page])
    end
  end

  def help
  end

  def about
  end

  def contact
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  before_action :logged_in_user, only: [:index, :edit, :update, :destroy, :following, :followers]
  def index
    @users = User.paginate(page: params[:page])
  end

  def show
    @user = User.find(params[:id])
    @microposts = @user.microposts.paginate(page: params[:page])
  end

  def new
    @user = User.new
  end

  def create
    @user = User.new(user_params)
    if @user.save
      flash[:success] = "Welcome to Sample App!"
      redirect_to @user
    else
      render 'new'
    end
  end

  def edit
    @user = User.find(params[:id])
  end

  def update
    @user = User.find(params[:id])
    if @user.update(user_params)
      flash[:success] = "Information Updated successfully"
      redirect_to @user
    else
      puts @user.errors.full_messages
      render 'edit'
    end
  end

  def destroy
    User.find(params[:id]).destroy
    flash[:success] = "User Deleted"
    redirect_to users_url
  end

  def following
    @title = "Following"
    @user = User.find(params[:id])
    @users = @user.following.paginate(page: params[:page])
    render 'show_follow', status: :unprocessable_entity
  end

  def followers
    @title = "Followers"
    @user = User.find(params[:id])
    @users = @user.followers.paginate(page: params[:page])
    render 'show_follow', status: :unprocessable_entity
  end

  private
    def user_params
      params.require(:user).permit(:name, :email, :password, :password_confirmation)
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
    # def full_title(page_title = "")
    #     base_title = "Ruby on Rails App"
    #     if page_title.empty?
    #         base_title
    #     else
    #         "#{page_title} | #{base_title}"
    #     end
    # end
end

app/helpers/microposts_helper.rb
module MicropostsHelper
end

app/helpers/relationships_helper.rb
module RelationshipsHelper
end

app/helpers/sessions_helper.rb
module SessionsHelper
    def log_in(user)
        session[:user_id] = user.id
    end

    def current_user
        @current_user ||= User.find_by(id: session[:user_id])
    end

    def logged_in?
        !current_user.nil?
    end

    def log_out
        session.delete(:user_id)
        @current_user = nil
    end

    def current_user?(user)
    user == current_user
  end
end

app/helpers/static_pages_helper.rb
module StaticPagesHelper
end

app/helpers/users_helper.rb
module UsersHelper
    def gravatar_for(user, options = { size: 80 })
        gravatar_id = Digest::MD5::hexdigest(user.email.downcase)
        size = options[:size]
        gravatar_url = "https://secure.gravatar.com/avatar/#{gravatar_id}?s=#{size}"
        image_tag(gravatar_url, alt: user.name, class: "gravatar")
    end
end

app/views/layouts/_footer.html.erb
<footer class="footer">
    <small>
        The Sample App by Huzaifa
    </small>
    <nav>
        <ul>
            <li><%= link_to "About", about_path%> </li>
            <li><%= link_to "Contact", contact_path%></li>
            <li><a href="www.google.com">News</a></li>
    </nav>
</footer>

app/views/layouts/_header.html.erb
<header class=" navbar navbar-fixed-top navbar-inverse one">
    <div class="container">
        <%= link_to "sample app", root_path , id:"logo"%>
        <nav>
            <ul class="nav justify-content-end">
                <li class="nav-item">
                    <%= link_to "Home", root_path, class: "nav-link" %>
                </li>
                <li class="nav-item">
                    <%= link_to "Help", help_path, class: "nav-link" %>
                </li>
                <% if logged_in? %>
                    <li class="nav-item">
                    <%= link_to "Users", users_path , class: "nav-link" %>
                    </li>
                    <li class="nav-item dropdown">
                    <a href="#" id="account" class="nav-link dropdown-toggle" role="button" data-bs-toggle="dropdown" aria-expanded="false">
                        Account <b class="caret"></b>
                    </a>
                    <ul class="dropdown-menu dropdown-menu-end" aria-labelledby="account">
                        <li><%= link_to "Profile", current_user, class: "dropdown-item" %></li>
                        <li><%= link_to "Settings", edit_user_path(current_user), class: "dropdown-item" %></li>
                        <li><hr class="dropdown-divider"></li>
                        <li><%= button_to "Log out", logout_path, method: :delete, class: "dropdown-item" %></li>
                    </ul>
                    </li>
                <% else %>
                    <li class="nav-item">
                    <%= link_to "Log in", login_path, class: "nav-link" %>
                    </li>
                <% end %>
            </ul>
        </nav>
    </div>
</header>

app/views/layouts/_shim.html.erb
<!--[if lt IE 9]>
  <script src="//cdnjs.cloudflare.com/ajax/libs/html5shiv/r29/html5.min.js">
  </script>
<![endif]-->

app/views/layouts/application.html.erb
<!DOCTYPE>
<html>
    <head>
    <title><%= yield(:title) %> | Sample App </title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <meta name="apple-mobile-web-app-capable" content="yes">
    <meta name="mobile-web-app-capable" content="yes">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= yield :head %>

    <%# Enable PWA manifest for installable apps (make sure to enable in config/routes.rb too!) %>
    <%#= tag.link rel: "manifest", href: pwa_manifest_path(format: :json) %>

    <link rel="icon" href="/icon.png" type="image/png">
    <link rel="icon" href="/icon.svg" type="image/svg+xml">
    <link rel="apple-touch-icon" href="/icon.png">

    <%# Includes all stylesheet files in app/assets/stylesheets %>
    <%= stylesheet_link_tag "application", media: "all", "data-turbo-track": "reload" %>

    <%= javascript_importmap_tags %>
    <%= render 'layouts/shim'%>
  </head>

  <body>
    <%= render "layouts/header"%>
    <div class="container">
      <% flash.each do |msg_type, msg| %>
        <div class="alert alert-<%=msg_type%>">
          <%= msg %>
        </div>
      <% end %>
      <%= yield %>
      <%= render "layouts/footer"%>
    </div>
  </body>
</html>

app/views/microposts/_form.html.erb
<%= form_with(model: micropost) do |form| %>
  <% if micropost.errors.any? %>
    <div style="color: red">
      <h2><%= pluralize(micropost.errors.count, "error") %> prohibited this micropost from being saved:</h2>

      <ul>
        <% micropost.errors.each do |error| %>
          <li><%= error.full_message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div>
    <%= form.label :content, style: "display: block" %>
    <%= form.textarea :content %>
  </div>

  <div>
    <%= form.label :user_id, style: "display: block" %>
    <%= form.number_field :user_id %>
  </div>

  <div>
    <%= form.submit %>
  </div>
<% end %>

app/views/microposts/_micropost.html.erb
<li id="micropost-<%= micropost.id%>">
    <%= link_to gravatar_for(micropost.user, size: 50), micropost.user %>
    <span class="user"><%= link_to micropost.user.name, micropost.user %></span>
    <span class="content"><%= micropost.content %></span>
    <span class="timestamp">
        Posted <%= time_ago_in_words(micropost.created_at) %> ago.
        <%= link_to "delete", micropost, data: { "turbo-method": :delete, turbo_confirm: "Are you sure?" } %>
    </span>
</li>

app/views/microposts/edit.html.erb
<% content_for :title, "Editing micropost" %>

<h1>Editing micropost</h1>

<%= render "form", micropost: @micropost %>

<br>

<div>
  <%= link_to "Show this micropost", @micropost %> |
  <%= link_to "Back to microposts", microposts_path %>
</div>

app/views/microposts/index.html.erb
<p style="color: green"><%= notice %></p>

<% content_for :title, "Microposts" %>

<h1>Microposts</h1>

<div id="microposts">
  <% @microposts.each do |micropost| %>
    <%= render micropost %>
    <p>
      <%= link_to "Show this micropost", micropost %>
    </p>
  <% end %>
</div>

<%= link_to "New micropost", new_micropost_path %>

app/views/microposts/new.html.erb
<% content_for :title, "New micropost" %>

<h1>New micropost</h1>

<%= render "form", micropost: @micropost %>

<br>

<div>
  <%= link_to "Back to microposts", microposts_path %>
</div>

app/views/microposts/show.html.erb
<p style="color: green"><%= notice %></p>

<%= render @micropost %>

<div>
  <%= link_to "Edit this micropost", edit_micropost_path(@micropost) %> |
  <%= link_to "Back to microposts", microposts_path %>

  <%= button_to "Destroy this micropost", @micropost, method: :delete %>
</div>

app/views/shared/_error_messages.html.erb
<% if object && object.errors.any? %>
  <div id="error_explanation">
    <div class="alert alert-danger">
      The form contains <%= pluralize(object.errors.count, "error") %>.
    </div>
    <ul>
      <% object.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
    </ul>
  </div>
<% end %>

app/views/shared/_feed.html.erb
<% if @feed_items.any? %>
  <ol class="microposts">
    <%= render @feed_items %>
  </ol>
  <%= will_paginate @feed_items, renderer: BootstrapPagination::Rails%>
<% end %>

app/views/shared/_micropost_form.html.erb
<%= form_with(model: @micropost) do |f| %>
  <%= render 'shared/error_messages', object: f.object %>
  <div class="field">
    <%= f.text_area :content, placeholder: "Compose new micropost..." %>
  </div>
  <%= f.submit "Post", class: "btn btn-primary" %>
<% end %>

app/views/shared/_stats.html.erb
<% @user ||= current_user %>
<div class="stats">
  <a href="<%= following_user_path(@user) %>">
    <strong id="following" class="stat">
      <%= @user.following.count %>
    </strong>
    following
  </a>
  <a href="<%= followers_user_path(@user) %>">
    <strong id="followers" class="stat">
      <%= @user.followers.count %>
    </strong>
    followers
  </a>
</div>

app/views/shared/_user_info.html.erb
<%= link_to gravatar_for(current_user, size: 50), current_user %>
<h1><%= current_user.name %></h1>
<span><%= link_to "view my profile", current_user %></span>
<span><%= pluralize(current_user.microposts.count, "micropost") %></span>

app/views/static_pages/about.html.erb
<% provide(:title, "About") %>

<h1>About the Sample App</h1>

<p>The Sample App is a simple Ruby on Rails project designed to demonstrate key features of a social networking site. It allows users to:</p>

<ul>
  <li>Create an account and log in securely</li>
  <li>Post short updates (microposts)</li>
  <li>Follow and unfollow other users</li>
  <li>View a feed of updates from people they follow</li>
</ul>

<p>This app was built as part of the Ruby on Rails Tutorial to help developers learn best practices in full-stack web development.</p>

app/views/static_pages/contact.html.erb
<% provide(:title, "Contact") %>

<h1>Contact</h1>

<p>
  Have questions or feedback? Feel free to reach out!
</p>

<ul>
  <li><strong>Email:</strong> <a href="mailto:huzaifaalam@arizona.edu">huzaifaalam@arizona.edu</a></li>
  <li><strong>GitHub:</strong> <a href="https://github.com/huzaifaalam1" target="_blank">github.com/huzaifaalam1</a></li>
  <li><strong>LinkedIn:</strong> <a href="https://www.linkedin.com/in/-huzaifa-alam" target="_blank">linkedin.com/in/-huzaifa-alam</a></li>
  <li><strong>Website:</strong> <a href="https://personal-portfolio-chi-fawn.vercel.app/" target="_blank">personalportfolio.com</a></li>
</ul>

<p>
  This sample app was built with Ruby on Rails as part of a learning project. Your feedback is welcome!
</p>

app/views/static_pages/help.html.erb
<h1>Help</h1>

<p>Welcome to the Help page for the Sample App!</p>

<h3>Frequently Asked Questions</h3>
<ul>
  <li><strong>How do I sign up?</strong> – Visit the <%= link_to "Sign Up", signup_path %> page and fill in your information.</li>
  <li><strong>How do I log in?</strong> – Go to the <%= link_to "Log In", login_path %> page and enter your credentials.</li>
  <li><strong>How do I post a micropost?</strong> – After logging in, use the form on the home page to share what's on your mind.</li>
  <li><strong>How do I follow other users?</strong> – Visit another user's profile and click the "Follow" button.</li>
</ul>

<p>If you're still having trouble, please contact support at <a href="mailto:huzaifaalam@arizona.edu">huzaifaalam@arizona.edu</a>.</p>

app/views/static_pages/home.html.erb
<% if logged_in? %>
  <div class="row">
    <aside class="col-md-4">
      <section class="user_info">
        <%= render 'shared/user_info' %>
      </section>
      <section class="stats">
        <%= render 'shared/stats' %>
      </section>
      <section class="micropost_form">
        <%= render 'shared/micropost_form' %>
      </section>
    </aside>
    <div class="col-md-8">
      <h3>Micropost Feed</h3>
      <%= render 'shared/feed' %>
    </div>
  </div>
<% else %>
    <div class="center jumbotron">
        <h1>Welcome to the Twitter Sample App</h1>

        <h2>This is the home page for the <a href="#">Sample App</a></h2>

        <%= link_to "Sign up now!", signup_path, class:"btn btn-lg btn-primary" %>
    </div>
<% end %>

app/views/users/_follow.html.erb
<%= form_with(model: current_user.active_relationships.build) do |f| %>
  <div><%= hidden_field_tag :followed_id, @user.id %></div>
  <%= f.submit "Follow", class: "btn btn-primary" %>
<% end %>

app/views/users/_follow_form.html.erb
<% unless current_user?(@user) %>
  <div id="follow_form">
  <% if current_user.following?(@user) %>
    <%= render 'unfollow' %>
  <% else %>
    <%= render 'follow' %>
  <% end %>
  </div>
<% end %>

app/views/users/_form.html.erb
<%= form_with(model: user) do |form| %>
  <% if user.errors.any? %>
    <div style="color: red">
      <h2><%= pluralize(user.errors.count, "error") %> prohibited this user from being saved:</h2>

      <ul>
        <% user.errors.each do |error| %>
          <li><%= error.full_message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div>
    <%= form.label :name, style: "display: block" %>
    <%= form.text_field :name %>
  </div>

  <div>
    <%= form.label :id, style: "display: block" %>
    <%= form.text_field :id %>
  </div>

  <div>
    <%= form.submit %>
  </div>
<% end %>

app/views/users/_unfollow.html.erb
<%= form_with(model: current_user.active_relationships.find_by(followed: @user),
html: { method: :delete }) do |f| %>
  <%= f.submit "Unfollow", class: "btn btn-secondary" %>
<% end %>

app/views/users/_user.html.erb
<li>
  <%= gravatar_for user, size: 50 %>
  <%= link_to user.name, user %>
</li>

app/views/users/edit.html.erb
<h1 class="mt-4">Update your profile</h1>
<div class="row">
    <div class="col-md-6 mx-auto">
        <%= form_for(@user, data: { turbo: false }) do |f| %>
            <%= render 'shared/error_messages', object: f.object%>

            <%= f.label :name %>
            <%= f.text_field :name, class: "form-control"%>

            <%= f.label :email %>
            <%= f.text_field :email, class: "form-control"%>

            <%= f.label :password %>
            <%= f.password_field :password, class: "form-control" %>

            <%= f.label :password_confirmation, "Confirm Password" %>
            <%= f.password_field :password_confirmation, class: "form-control" %>

            <%= f.submit "Save changes", class: "btn btn-primary" %>
        <% end %>
        <div class="gravatar_edit">
            <%= gravatar_for @user %>
            <a href="http://gravatar.com/emails">Change
            </a>
        </div>

    </div>
</div>

app/views/users/index.html.erb
<h1>All Users</h1>
<ul class="users">
    <% @users.each do |user| %>
        <li>
            <%= gravatar_for user, size: 50 %>
            <%= link_to user.name, user %>
            <% if current_user.admin? && !current_user?(user) %>
                | <%= link_to "delete", user, method: :delete,
                data: { confirm: "Are you sure you want to delete this user?", turbo: false} %>
            <% end %>
        </li>
    <% end %>
</ul>

<%= will_paginate @users, renderer: BootstrapPagination::Rails %>

app/views/users/new.html.erb
<h1 class="mt-4">Sign Up</h1>
<div class="row">
    <div class="col-md-6 mx-auto">
         <%= form_for(@user, data: { turbo: false }) do |f| %>
            <%= render 'shared/error_messages', object: f.object %>
            <%= f.label :name %>
            <%= f.text_field :name, class: "form-control"%>

            <%= f.label :email %>
            <%= f.text_field :email, class: "form-control"%>

            <%= f.label :password %>
            <%= f.password_field :password, class: "form-control" %>

            <%= f.label :password_confirmation, "Confirm Password" %>
            <%= f.password_field :password_confirmation, class: "form-control" %>

            <%= f.submit "Create my account", class: "btn btn-primary" %>
        <% end %>
    </div>
</div>

app/views/users/show.html.erb
<% provide(:title, @user.name) %>
<div class="row">
    <aside class="col-md-4">
        <section class="user_info">
            <h1>
                <%= gravatar_for @user %>
                <%= @user.name %>
            </h1>
        </section>
        <section class="stats">
            <%= render 'shared/stats' %>
        </section>
    </aside>
    <div class="col-md-8">
        <%= render 'follow_form' if logged_in? %>
        <% if @user.microposts.any? %>
            <h3>Microposts (<%= @user.microposts.count %>)</h3>
            <ol class="microposts">
                <%= render @microposts %>
            </ol>
            <%= will_paginate @microposts, renderer: BootstrapPagination::Rails %>
        <% end %>
    </div>
</div>

app/views/users/show_follow.html.erb
<div class="row">
  <aside class="col-md-4">
    <section class="user_info">
      <%= gravatar_for @user %>
      <h1><%= @user.name %></h1>
      <span><%= link_to "view my profile", @user %></span>
      <span><strong>Microposts:</strong> <%= @user.microposts.count %></span>
    </section>
    <section class="stats">
      <%= render 'shared/stats' %>
      <% if @users.any? %>
        <div class="user_avatars">
          <% @users.each do |user| %>
            <%= link_to gravatar_for(user, size: 30), user %>
          <% end %>
        </div>
      <% end %>
    </section>
  </aside>
  <div class="col-md-8">
    <h3><%= @title %></h3>
    <% if @users.any? %>
      <ul class="users follow">
        <%= render @users %>
      </ul>
      <%= will_paginate(@users, renderer: BootstrapPagination::Rails) %>
    <% end %>
  </div>
</div>